# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       mer-not-a-ux

# >> macros
# << macros

Summary:    A simple example of a basic UX package
Version:    0.2
Release:    1
Group:      System/GUI/Other
License:    GPL
Source0:    mer-not-a-ux-%{version}.tar.gz
Source100:  mer-not-a-ux.yaml
Requires:   qt5-qtdeclarative-qmlscene
Requires:   qt5-qtdeclarative-import-qtquick2plugin
Requires:   qt5-plugin-platform-xcb
Requires:   qt5-plugin-imageformat-jpeg

%description
Demonstrates integration with uxlaunch and provides a base to evolve a custom UI

%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/mer-not-a-ux/*
%{_bindir}/minimer
# >> files
# << files
